# Count how many genes in our dataset are annotated as essential

In [ ]:
import pandas as pd
import numpy as np
from bson import decode_all

In [4]:
df_wt = pd.read_csv("../../data/metadata/wt_sequences.csv")
df_wt.head()

,genes,sequence,promoter,promoter_seq,fwd_primer,rev_primer1,rev_primer2,rev_primer3,upstream_re_site,downstream_re_site,name
0,"[""rspA"", ""rspB""]",ACCTGTAATTCCAAGCGTCTACTAGTTTTCATCTTTTGTCAACCAT...,rspAp,TTTCATCTTTTGTCAACCATTCACAGCGCAAATATACGCCTTTTTT...,"(100, (1, 20))","(100, (231, 250))","(101, (193, 211))","(202, (212, 230))",SpeI,ApaI,rspAp_0
1,"[""araA"", ""araB"", ""araD""]",ACCTGTAATTCCAAGCGTCTACTAGTTCCACATTGATTATTTGCAC...,araBp,TCCACATTGATTATTTGCACGGCGTCACACTTTGCTATGCCATAGC...,"(100, (1, 20))","(100, (231, 250))","(101, (193, 211))","(202, (212, 230))",SpeI,ApaI,araBp_0
2,"[""znuB"", ""znuC""]",ACCTGTAATTCCAAGCGTCTACTAGTGTGTTGCACCTCCCCAGAGA...,znuCp,GTGTTGCACCTCCCCAGAGAGCGGCGGATAATGCTGCGAAAAGAAG...,"(100, (1, 20))","(100, (231, 250))","(101, (193, 211))","(202, (212, 230))",SpeI,ApaI,znuCp_0
3,"[""xylA"", ""xylB""]",ACCTGTAATTCCAAGCGTCTACTAGTCCAGTTTCATCATTCCATTT...,xylAp,CCAGTTTCATCATTCCATTTTATTTTGCGAGCGAGCGCACACTTGT...,"(100, (1, 20))","(100, (231, 250))","(101, (193, 211))","(202, (212, 230))",SpeI,ApaI,xylAp_0
4,"[""xylF"", ""xylG"", ""xylH"", ""xylR""]",ACCTGTAATTCCAAGCGTCTACTAGTAATTGCGCAACAAAAGTAAG...,xylFp,AATTGCGCAACAAAAGTAAGATCTCGGTCATAAATCAAGAAATAAA...,"(100, (1, 20))","(100, (231, 250))","(101, (193, 211))","(202, (212, 230))",SpeI,ApaI,xylFp_0

In [5]:
df = pd.read_csv("../../data/metadata/essential_genes.csv", header=1)
df = df[df['Essential'] == True]
df['Gene']

21      rpsT
23      ribF
24      ileS
25      lspA
27      ispH
        ...
4170    lptF
4171    lptG
4271    dnaC
4272    dnaT
4280    holD
Name: Gene, Length: 356, dtype: object

In [16]:
df[[np.any([y in x for x in df_wt.genes]) for y in df['Gene']]]

,Gene,Insertion Index Score,Log Likelihood Ratio,Essential,Non-essential,Unclear
625,ybeD,0.000000,-173.551740,True,False,False
668,fldA,0.000000,-173.551740,True,False,False
1111,icd,0.014388,-4.310430,True,False,False
1550,relB,0.012500,-5.142316,True,False,False
1556,dicA,0.000000,-173.551740,True,False,False
1698,ihfA,0.010000,-6.351668,True,False,False
1699,pheT,0.000838,-15.654914,True,False,False
1700,pheS,0.000000,-173.551740,True,False,False
1701,pheM,0.000000,-173.551740,True,False,False
2209,gyrA,0.003425,-10.952880,True,False,False
3291,crp,0.014218,-4.383234,True,False,False

Additionally we can check which transcription factors are essential.

In [2]:
df_TFs = pd.read_csv("../../data/metadata/all_tfs.csv")
df_TFs

    Gene Name Family Previous/Alternative Name
0        acrR   TetR                       NaN
1         ada   AraC                       NaN
2        adiY   AraC                       NaN
3        agaR   DeoR                       NaN
4        allR   IclR                       NaN
..        ...    ...                       ...
282      yqjI   GntR                       NaN
283      ytfH   MarR                       NaN
284      zntR   MerR                       NaN
285      zraR   NtrC                       NaN
286       zur    Fur                       NaN

[287 rows x 3 columns]

In [15]:
df_TF_alt = df_TFs.dropna()
df_TF_alt

    Gene Name Family Previous/Alternative Name
10       argP   LysR                      yfdC
18       bdcR   TetR                      yjgJ
22       bluR   MerR                      yfcO
24       btsR   LysR                      ypdA
30       cecR   TetR                      ybiH
32       chpS   GntR                      yieP
34       comR   TetR                      ycfQ
36        cra   LacI                      fruR
42       csqR   DeoR                      yihW
48        dan   LysR                      ygiP
51       decR   AsnC                      ybaO
58       dmlR   LysR                      ybdO
63       eidR   LysR                      ycaN
64       emrR   MarR                      mprA
84       frmR   FrmR                      rcnR
88       gadE   LuxR                      yhiE
98       gprR   GntR                      ydcR
155      nemR   TetR                      ydhM
158      nimR   AraC                      ybcM
170      pgrR   LysR                      ycjZ
171      phhR   AraC                      ydeO
175      plaR   IclR                      yiaJ
178      pucR   AraC                      yqhC
188      rcdA   TetR                      ybjK
193      rdrA   LysR                      yhaJ
202      rutR   TetR                      ycdC
212      srsR   LysR                      ygfI
214      sutR    Xre                      ydcN
227      xynR   TetR                      yagI

In [6]:
pd.merge(df_TFs, df, right_on='Gene', left_on='Gene Name', how='inner')

,Gene Name,Family,Previous/Alternative Name,Gene,Insertion Index Score,Log Likelihood Ratio,Essential,Non-essential,Unclear
0,birA,BirA,NaN,birA,0.014493,-4.266106,True,False,False
1,crp,Crp,NaN,crp,0.014218,-4.383234,True,False,False
2,dicA,Xre,NaN,dicA,0.000000,-173.551740,True,False,False
3,dnaA,DnaA,NaN,dnaA,0.000712,-16.157557,True,False,False
4,higA,Xre,NaN,higA,0.009592,-6.564215,True,False,False
5,hipB,Xre,NaN,hipB,0.003745,-10.619334,True,False,False
6,ihfA,HU,NaN,ihfA,0.010000,-6.351668,True,False,False
7,lexA,LexA,NaN,lexA,0.014778,-4.145479,True,False,False
8,racR,Xre,NaN,racR,0.008386,-7.226236,True,False,False
9,relB,Xre,NaN,relB,0.012500,-5.142316,True,False,False

In [8]:
pd.merge(df_TF_alt, df, right_on='Gene', left_on='Previous/Alternative Name', how='inner')

Empty DataFrame
Columns: [Gene Name, Family, Previous/Alternative Name, Gene, Insertion Index Score, Log Likelihood Ratio, Essential, Non-essential, Unclear]
Index: []

,Gene,Insertion Index Score,Log Likelihood Ratio,Essential,Non-essential,Unclear
625,ybeD,0.000000,-173.551740,True,False,False
668,fldA,0.000000,-173.551740,True,False,False
1111,icd,0.014388,-4.310430,True,False,False
1550,relB,0.012500,-5.142316,True,False,False
1556,dicA,0.000000,-173.551740,True,False,False
1698,ihfA,0.010000,-6.351668,True,False,False
1699,pheT,0.000838,-15.654914,True,False,False
1700,pheS,0.000000,-173.551740,True,False,False
1701,pheM,0.000000,-173.551740,True,False,False
2209,gyrA,0.003425,-10.952880,True,False,False
3291,crp,0.014218,-4.383234,True,False,False